### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by sameer-kumar** [Homely/Homely.AspNetCore.Mvc.Helpers#28]
I can't get AddProblemDetails() to work. Is this something not yet baked in or am i missing something?

**Comment by PureKrome** [comment]
👋🏻 Hi @sameer-kumar - sincerly sorry for the slow reply. I totally didn't get this message, so it fell under my radar.

Are you still having issues with `AddProblemDetails()` ?

**Comment by sameer-kumar** [comment]
No worries. I forgot it too. Looks like when I was evaluating it, I couldn't figure it out. You can close the issue as I no longer need it. Thanks for following up though.

**Comment by PureKrome** [comment]
No probs. Maybe another time you could have a look at it, again. Docs are updated, too.
